(n  /visit routes
    when the user is staff
      ✓ should forbid getting the create form
      ✓ should forbid posting create data
      ✓ should forbid getting the update form
      ✓ should forbid postierror: Sending 500 ("Server Error") response: 
 AdapterError: Unexpected error from database adapter: Internal error occurred while running `join`.  Got non-Error:   1) "after all" hook

  7 passing (4s)
  1 failing

  1) "after all" hook:

      Uncaught AssertionError: expected 500 to be 200
      + expected - actual

      -500
      +200
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at ClientRequest.<anonymous> (test/CheckHTTP.js:48:44)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
      at Socket.socketOnData (_http_client.js:451:20)
      at addChunk (_stream_readable.js:288:12)
      at readableAddChunk (_stream_readable.js:269:11)
      at Socket.Readable.push (_stream_readable.js:224:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)



n/spawn-connection.js:29:10)
       at Object.spawnOrLeaseConnection (/workspace/nlcAttendance/node_modules/sails-mysql/helpers/private/connection/spawn-or-lease-connection.js:23:3)
       at Object.join (/workspace/nlcAttendance/node_modules/sails-mysql/helpers/join.js:135:24)
       at wrapper (/workspace/nlcAttendance/node_modules/@sailshq/lodash/lib/index.js:3282:19)
       at Deferred.parley.retry [as _handleExec] (/workspace/nlcAttendance/node_modules/machine/lib/private/help-build-machine.js:1076:19)
       at Deferred.exec (/workspace/nlcAttendance/node_modules/parley/lib/private/Deferred.js:286:10)
       at Deferred.switch (/workspace/nlcAttendance/node_modules/machine/lib/private/help-build-machine.js:1469:16)
       at Object.join (/workspace/nlcAttendance/node_modules/sails-mysql/lib/adapter.js:264:16)
       at _getPopulatedRecords (/workspace/nlcAttendance/node_modules/waterline/lib/waterline/utils/query/help-find.js:128:21)
       at helpFind (/workspace/nlcAttendance/node_modules/waterline/lib/waterline/utils/query/help-find.js:582:6)
       at _afterPotentiallyRunningBeforeLC (/workspace/nlcAttendance/node_modules/waterline/lib/waterline/methods/find-one.js:265:9)
       at _maybeRunBeforeLC (/workspace/nlcAttendance/node_modules/waterline/lib/waterline/methods/find-one.js:239:16)
       at Deferred._.extend._WLModel [as _handleExec] (/workspace/nlcAttendance/node_modules/waterline/lib/waterline/methods/find-one.js:241:9)
       at Deferred.exec (/workspace/nlcAttendance/node_modules/parley/lib/private/Deferred.js:286:10)
       at Deferred.tryCatcher (/workspace/nlcAttendance/node_modules/bluebird/js/release/util.js:11:23)
       at ret (eval at makeNodePromisifiedEval (/workspace/nlcAttendance/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
       at Deferred.toPromise (/workspace/nlcAttendance/node_modules/parley/lib/private/Deferred.js:572:19)
       at Deferred.then (/workspace/nlcAttendance/node_modules/parley/lib/private/Deferred.js:431:22)
       at process._tickCallback (internal/process/next_tick.js:68:7) code: 'POOL_CLOSED' },
  meta:
   { host: 'localhost',
     port: 3306,
     schema: true,
     adapter: 'sails-mysql',
     url: 'mysql://nlc:password@localhost:3306/nlcAttendance',
     identity: 'default' } }

If you are the maintainer of "join", then you can change its implementation to solve the problem (Most of the time, the solution is just to throw an actual Error instance instead.  Alternatively, if the goal was to indicate a particular exception, you could throw any of the special, reserved "exit signals"-- e.g. the code name of any of your defined exits besides "error" or "success").  Otherwise, please file a bug report with the maintainer, or fork your own copy and fix that.
 [?] See https://sailsjs.com/support for help.
    at Object.fn (/workspace/nlcAttendance/api/controllers/visit/download.js:33:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:1337
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
